import 'dart:convert';
import 'dart:io';

import 'package:clawchat/models/chat_models.dart';
import 'package:clawchat/services/session_storage.dart';
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:shared_preferences/shared_preferences.dart';

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  const pathProviderChannel = MethodChannel('plugins.flutter.io/path_provider');
  late Directory tempDir;

  setUp(() async {
    SharedPreferences.setMockInitialValues({});
    tempDir = await Directory.systemTemp.createTemp('clawchat_session_test_');
    TestDefaultBinaryMessengerBinding.instance.defaultBinaryMessenger
        .setMockMethodCallHandler(pathProviderChannel, (call) async {
      if (call.method == 'getApplicationDocumentsDirectory') {
        return tempDir.path;
      }
      return null;
    });
  });

  tearDown(() async {
    TestDefaultBinaryMessengerBinding.instance.defaultBinaryMessenger
        .setMockMethodCallHandler(pathProviderChannel, null);
    if (await tempDir.exists()) {
      await tempDir.delete(recursive: true);
    }
  });

  group('SessionStorage session ID safety', () {
    test('valid UUID-like IDs are accepted', () async {
      final storage = SessionStorage();
      await storage.init();
      final session = ChatSession(
        id: 'session_123-abc',
        title: 'Valid',
        messages: [ChatMessage.user('hello')],
      );

      await storage.saveSession(session);

      final loaded = await storage.getSession('session_123-abc');
      expect(loaded?.id, 'session_123-abc');
      expect(await storage.getSessionIds(), contains('session_123-abc'));
    });

    test('path traversal IDs are regenerated by ChatSession parsing', () {
      final session = ChatSession.fromJson(_sessionJson('../escape'));

      expect(session.id, isNot('../escape'));
      expect(session.id, matches(RegExp(r'^[a-zA-Z0-9_-]+$')));
    });

    test('invalid IDs cannot be loaded directly', () async {
      final storage = SessionStorage();
      await storage.init();

      expect(await storage.getSession('../escape'), isNull);
      expect(await storage.getSession('nested/path'), isNull);
    });

    test('import with invalid IDs writes only safe session files', () async {
      final storage = SessionStorage();
      await storage.init();
      final count = await storage.importFromJson(jsonEncode({
        'version': 1,
        'sessions': [_sessionJson('../../outside')],
      }));

      expect(count, 1);
      final sessionsDir = Directory('${tempDir.path}/clawchat_sessions');
      final files = await sessionsDir
          .list()
          .where((entity) => entity is File && entity.path.endsWith('.json'))
          .cast<File>()
          .toList();

      expect(files, hasLength(1));
      expect(files.single.parent.path, sessionsDir.path);
      expect(files.single.uri.pathSegments.last, isNot(contains('..')));
      expect(files.single.uri.pathSegments.last, isNot(contains('/')));
    });
  });
}

Map<String, dynamic> _sessionJson(String id) {
  return {
    'id': id,
    'title': 'Imported',
    'createdAt': DateTime(2026, 1, 1).toIso8601String(),
    'updatedAt': DateTime(2026, 1, 1).toIso8601String(),
    'messages': [
      {
        'role': 'user',
        'timestamp': DateTime(2026, 1, 1).toIso8601String(),
        'content': [
          {'type': 'text', 'text': 'hello'}
        ],
      }
    ],
  };
}
