import 'dart:convert';
import 'dart:io';

import 'package:clawchat/models/chat_models.dart';
import 'package:clawchat/services/session_storage.dart';
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:shared_preferences/shared_preferences.dart';

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  const pathProviderChannel = MethodChannel('plugins.flutter.io/path_provider');
  late Directory tempDir;

  setUp(() async {
    SharedPreferences.setMockInitialValues({});
    tempDir = await Directory.systemTemp.createTemp('clawchat_session_test_');
    TestDefaultBinaryMessengerBinding.instance.defaultBinaryMessenger
        .setMockMethodCallHandler(pathProviderChannel, (call) async {
      if (call.method == 'getApplicationDocumentsDirectory') {
        return tempDir.path;
      }
      return null;
    });
  });

  tearDown(() async {
    TestDefaultBinaryMessengerBinding.instance.defaultBinaryMessenger
        .setMockMethodCallHandler(pathProviderChannel, null);
    if (await tempDir.exists()) {
      await tempDir.delete(recursive: true);
    }
  });

  group('SessionStorage session ID safety', () {
    test('valid UUID-like IDs are accepted', () async {
      final storage = SessionStorage();
      await storage.init();
      final session = ChatSession(
        id: 'session_123-abc',
        title: 'Valid',
        messages: [ChatMessage.user('hello')],
      );

      await storage.saveSession(session);

      final loaded = await storage.getSession('session_123-abc');
      expect(loaded?.id, 'session_123-abc');
      expect(await storage.getSessionIds(), contains('session_123-abc'));
    });

    test('atomic save keeps backup and restores readable backup', () async {
      final storage = SessionStorage();
      await storage.init();
      final session = ChatSession(
        id: 'atomic_session',
        title: 'Original',
        messages: [ChatMessage.user('hello')],
      );
      await storage.saveSession(session);

      session.title = 'Updated';
      await storage.saveSession(session);

      final sessionsDir = Directory('${tempDir.path}/clawchat_sessions');
      final primary = File('${sessionsDir.path}/atomic_session.json');
      final backup = File('${primary.path}.bak');
      expect(await primary.exists(), isTrue);
      expect(await backup.exists(), isTrue);
      expect(
        ChatSession.fromJson(
          jsonDecode(await backup.readAsString()) as Map<String, dynamic>,
        ).title,
        'Original',
      );

      await primary.writeAsString('{not valid json');

      final recovered = await storage.getSession('atomic_session');

      expect(recovered?.title, 'Original');
      expect(await primary.readAsString(), await backup.readAsString());
      final quarantined = await sessionsDir
          .list()
          .where(
              (entity) => entity.path.contains('atomic_session.json.corrupt'))
          .toList();
      expect(quarantined, isNotEmpty);
    });

    test('saveSession replaces existing primary and keeps previous backup',
        () async {
      final storage = SessionStorage();
      await storage.init();
      final session = ChatSession(
        id: 'replace_session',
        title: 'Before',
        messages: [ChatMessage.user('first version')],
      );
      await storage.saveSession(session);

      session.title = 'After';
      session.messages
        ..clear()
        ..add(ChatMessage.user('second version'));
      await storage.saveSession(session);

      final loaded = await storage.getSession('replace_session');
      expect(loaded?.title, 'After');
      expect(loaded?.messages.single.textContent, 'second version');

      final backup = File(
        '${tempDir.path}/clawchat_sessions/replace_session.json.bak',
      );
      final backupSession = ChatSession.fromJson(
        jsonDecode(await backup.readAsString()) as Map<String, dynamic>,
      );
      expect(backupSession.title, 'Before');
      expect(backupSession.messages.single.textContent, 'first version');
    });

    test('path traversal IDs are regenerated by ChatSession parsing', () {
      final session = ChatSession.fromJson(_sessionJson('../escape'));

      expect(session.id, isNot('../escape'));
      expect(session.id, matches(RegExp(r'^[a-zA-Z0-9_-]+$')));
    });

    test('invalid IDs cannot be loaded directly', () async {
      final storage = SessionStorage();
      await storage.init();

      expect(await storage.getSession('../escape'), isNull);
      expect(await storage.getSession('nested/path'), isNull);
    });

    test('import with invalid IDs writes only safe session files', () async {
      final storage = SessionStorage();
      await storage.init();
      final count = await storage.importFromJson(jsonEncode({
        'version': 1,
        'sessions': [_sessionJson('../../outside')],
      }));

      expect(count, 1);
      final sessionsDir = Directory('${tempDir.path}/clawchat_sessions');
      final files = await sessionsDir
          .list()
          .where((entity) => entity is File && entity.path.endsWith('.json'))
          .cast<File>()
          .toList();

      expect(files, hasLength(1));
      expect(files.single.parent.path, sessionsDir.path);
      expect(files.single.uri.pathSegments.last, isNot(contains('..')));
      expect(files.single.uri.pathSegments.last, isNot(contains('/')));
    });

    test('import preserves existing session on id conflict', () async {
      final storage = SessionStorage();
      await storage.init();
      await storage.saveSession(ChatSession(
        id: 'same_id',
        title: 'Existing',
        messages: [ChatMessage.user('keep me')],
      ));

      final count = await storage.importFromJson(jsonEncode({
        'version': 1,
        'sessions': [
          _sessionJson(
            'same_id',
            title: 'Imported',
            messages: [
              ChatMessage.user('import me').toJson(),
            ],
          ),
        ],
      }));

      expect(count, 1);
      final existing = await storage.getSession('same_id');
      expect(existing?.title, 'Existing');
      expect(existing?.messages.single.textContent, 'keep me');

      final all = await storage.getAllSessions();
      expect(all, hasLength(2));
      final imported = all.singleWhere((session) => session.id != 'same_id');
      expect(imported.title, 'Imported (imported copy)');
      expect(imported.messages.single.textContent, 'import me');
    });
  });

  group('SessionStorage search', () {
    test('matches session message content and returns preview', () async {
      final storage = SessionStorage();
      await storage.init();
      final session = ChatSession(
        id: 'searchable',
        title: 'Daily notes',
        messages: [
          ChatMessage.user('hello'),
          ChatMessage(
            role: 'assistant',
            content: [
              TextContent('The deployment checklist mentions vector search.')
            ],
          ),
        ],
      );

      await storage.saveSession(session);

      final results = await storage.searchSessions('vector');
      expect(results.map((r) => r.summary.id), contains('searchable'));
      expect(results.first.matchPreview, contains('vector'));
    });

    test('uses backup for corrupted primary without mutating files', () async {
      final storage = SessionStorage();
      await storage.init();
      final session = ChatSession(
        id: 'search_backup',
        title: 'Backup searchable',
        messages: [ChatMessage.user('backup needle')],
      );
      await storage.saveSession(session);
      session.title = 'Primary current';
      session.messages
        ..clear()
        ..add(ChatMessage.user('current text'));
      await storage.saveSession(session);

      final sessionsDir = Directory('${tempDir.path}/clawchat_sessions');
      final primary = File('${sessionsDir.path}/search_backup.json');
      final backup = File('${primary.path}.bak');
      const corruptedPayload = '{not valid json';
      final backupBefore = await backup.readAsString();
      await primary.writeAsString(corruptedPayload);

      final results = await storage.searchSessions('needle');

      expect(results.map((result) => result.summary.id), ['search_backup']);
      expect(await primary.readAsString(), corruptedPayload);
      expect(await backup.readAsString(), backupBefore);
      final quarantined = await sessionsDir
          .list()
          .where((entity) => entity.path.contains('search_backup.json.corrupt'))
          .toList();
      expect(quarantined, isEmpty);
    });
  });

  group('SessionStorage preview', () {
    test('uses the active alternative text for message preview', () async {
      final storage = SessionStorage();
      await storage.init();
      final session = ChatSession(
        id: 'preview_alt',
        title: 'Preview',
        messages: [
          ChatMessage(
            role: 'assistant',
            content: [TextContent('latest')],
            alternatives: ['first'],
            activeAlternative: 0,
          ),
        ],
      );

      await storage.saveSession(session);

      final preview = await storage.getSessionPreview('preview_alt');
      expect(preview?.preview, 'first');
    });
  });

  group('SessionStorage usage summary', () {
    test('aggregates usage off stored payloads and skips corrupted sessions',
        () async {
      final storage = SessionStorage();
      await storage.init();
      await storage.saveSession(ChatSession(
        id: 'usage_one',
        title: 'Usage one',
        messages: [
          ChatMessage.user('hello'),
          ChatMessage(
            role: 'assistant',
            content: [TextContent('world')],
            inputTokens: 100,
            outputTokens: 20,
            cacheReadInputTokens: 30,
            cacheCreationInputTokens: 40,
          ),
        ],
      ));
      await storage.saveSession(ChatSession(
        id: 'usage_two',
        title: 'Usage two',
        messages: [
          ChatMessage(
            role: 'assistant',
            content: [TextContent('cached')],
            inputTokens: 50,
            outputTokens: 5,
            cacheReadInputTokens: 10,
            inputTokensIncludeCache: true,
          ),
          ChatMessage.systemNotice('ignored')
            ..inputTokens = 999
            ..outputTokens = 999,
        ],
      ));
      final corruptedFile = File(
        '${tempDir.path}/clawchat_sessions/corrupted.json',
      );
      await corruptedFile.writeAsString('{not valid json');

      final aggregate = await storage.getUsageSummaryAggregate();

      expect(await corruptedFile.exists(), isTrue);
      expect(aggregate.sessionCount, 2);
      expect(aggregate.summary.messageCount, 3);
      expect(aggregate.summary.messagesWithUsage, 2);
      expect(aggregate.summary.inputTokens, 150);
      expect(aggregate.summary.outputTokens, 25);
      expect(aggregate.summary.cacheReadInputTokens, 40);
      expect(aggregate.summary.cacheCreationInputTokens, 40);
      expect(aggregate.summary.totalTokens, 245);
    });
  });

  group('SessionStorage fork', () {
    test('copies messages through selected index and skips system notices',
        () async {
      final storage = SessionStorage();
      await storage.init();
      final source = ChatSession(
        id: 'source',
        title: 'Original',
        messages: [
          ChatMessage.user('first'),
          ChatMessage.systemNotice('context compacted'),
          ChatMessage(role: 'assistant', content: [TextContent('second')]),
          ChatMessage.user('third'),
        ],
      );
      await storage.saveSession(source);

      final fork = await storage.forkSession('source', 2);

      expect(fork, isNotNull);
      expect(fork!.id, isNot(source.id));
      expect(fork.title, '分支自: Original');
      expect(fork.messages.map((m) => m.textContent), ['first', 'second']);
      expect(fork.messages.any((m) => m.isSystemNotice), isFalse);

      fork.messages.first.content = [TextContent('changed')];
      final reloadedSource = await storage.getSession('source');
      expect(reloadedSource!.messages.first.textContent, 'first');
    });
  });

  group('ChatSession API messages', () {
    test('filters persisted system notices from API payload', () {
      final session = ChatSession(
        id: 'api_filter',
        messages: [
          ChatMessage.user('hello'),
          ChatMessage.systemNotice('对话上下文已压缩'),
          ChatMessage(role: 'assistant', content: [TextContent('hi')]),
        ],
      );

      final apiMessages = session.toApiMessages();
      expect(apiMessages, hasLength(2));
      expect(apiMessages.any((m) => m['role'] == 'system'), isFalse);
    });
  });
}

Map<String, dynamic> _sessionJson(
  String id, {
  String title = 'Imported',
  List<Map<String, dynamic>>? messages,
}) {
  return {
    'id': id,
    'title': title,
    'createdAt': DateTime(2026, 1, 1).toIso8601String(),
    'updatedAt': DateTime(2026, 1, 1).toIso8601String(),
    'messages': messages ??
        [
          {
            'role': 'user',
            'timestamp': DateTime(2026, 1, 1).toIso8601String(),
            'content': [
              {'type': 'text', 'text': 'hello'}
            ],
          }
        ],
  };
}
